default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: sample_development

test: &test
  <<: *default
  database: sample_test

production:
  <<: *default
  database: sample_production
